// HIGH RANK — EN-only copy, full landing brief
window.HR_COPY = {
  nav: {
    services: "Services",
    method: "Method",
    pricing: "Pricing",
    faq: "FAQ",
    cta: "Book an audit",
  },
  hero: {
    pill_tag: "Available",
    pill_text: "Independent SEO consultant — booking now",
    title_a: "Your SEO is stuck",
    title_em: "and you don't know why",
    title_b: ".",
    sub: "I find the hidden opportunities your tools miss. AI-powered analysis, expert-driven decisions.",
    cta_primary: "Request an audit",
    cta_secondary: "15-min call",
    meta: [
      { v: "3+ yrs", l: "agency-side" },
      { v: "20+ industries", l: "covered" },
      { v: "6 sites", l: "of my own" },
    ],
    kws: ["Programmatic SEO", "GEO / LLM visibility", "MCP", "Tech SEO", "Semantic", "Link building"],
    kw_hl: ["GEO / LLM visibility", "MCP", "Programmatic SEO"],
  },
  problem: {
    eyebrow: "The problem",
    title: "Why your SEO isn't moving.",
    items: [
      { num: "01", title: "You ran the free tools.", desc: "10,000 lines of Excel. Zero idea what to do first. The tools surface symptoms — not priorities." },
      { num: "02", title: "You read 20 SEO checklists.", desc: "Every one of them says something different. Half are outdated. None are written for your specific site." },
      { num: "03", title: "You asked your dev to fix it.", desc: "They shipped the changes. Traffic didn't move. SEO isn't an engineering ticket — it's a strategy." },
    ],
    conclusion_a: "SEO isn't one checklist. It's ",
    conclusion_em: "200 micro-decisions",
    conclusion_b: " that only experience knows how to make.",
  },
  solution: {
    eyebrow: "The method",
    title: "AI handles the volume. I handle the call.",
    sub: "Most consultants stop where the data dump ends. I start there.",
    cols: [
      {
        kind: "them",
        label: "Standard consultants",
        items: [
          "Crawl with off-the-shelf tools",
          "Hand you 10,000 rows of CSV",
          "\"Here are the issues — good luck\"",
          "Static report, no follow-up",
        ],
      },
      {
        kind: "us",
        label: "HIGH RANK",
        items: [
          "SEO expertise + custom AI models",
          "AI processes data, my brain ranks priorities",
          "Concrete action plan: quick wins + long-term plays",
          "Live tracking, weekly check-ins",
        ],
      },
    ],
    tagline_a: "AI ",
    tagline_em1: "detects",
    tagline_b: ". My expertise ",
    tagline_em2: "decides",
    tagline_c: ".",
  },
  diff: {
    eyebrow: "What I find",
    title: "What my audit catches that other tools miss.",
    items: [
      { num: "→", title: "Zombie pages cannibalizing your own content.", desc: "Pages competing against each other. Kill, merge, or reroute — I tell you which." },
      { num: "→", title: "Keywords ranking #11–20 with one push to top 10.", desc: "The fastest revenue you can ship in SEO. Most audits skip this entirely." },
      { num: "→", title: "Internal linking diluting your authority.", desc: "Your link equity is leaking. I show exactly where and how to redirect it." },
      { num: "→", title: "Content gaps vs your top-3 competitors.", desc: "What they rank on that you don't even cover. Prioritized by search intent and difficulty." },
    ],
    conclusion: "AI lets me process volumes a human can't. My expertise turns that into a plan that pays.",
  },
  services: {
    eyebrow: "Services",
    title: "How I can help.",
    sub: "Three ways to work together. Tell me your situation — I'll come back with a scoped proposal in 24h.",
    items: [
      {
        num: "01",
        code: "audit",
        title: "Complete SEO Audit",
        note: "Delivered in 3–5 days",
        bullets: [
          "Technical audit (architecture, crawl, performance)",
          "Semantic audit (keywords, content gaps, intent)",
          "Backlink audit (authority, profile, competitors)",
          "Prioritized action plan — not a 500-row Excel",
        ],
      },
      {
        num: "02",
        code: "audit-build",
        title: "Audit + 3-Month Build",
        note: "Audit + 3 months of execution",
        bullets: [
          "Everything in the complete audit",
          "Guided implementation for 3 months",
          "Monthly page-level optimization",
          "Qualified backlink acquisition",
        ],
      },
      {
        num: "03",
        code: "retainer",
        title: "Continuous Retainer",
        note: "Scoped to your business",
        bullets: [
          "Initial audit included",
          "Ongoing optimization across the site",
          "Transparent monthly reporting",
          "Monthly strategy call",
        ],
      },
    ],
  },
  form: {
    eyebrow: "Brief",
    title: "Tell me about your project.",
    sub: "No 12-field gauntlet. Drop your URL, your goal, and what's blocking you. I read every brief myself.",
    fields: {
      url_l: "Website URL",
      url_p: "https://yourdomain.com",
      name_l: "Your name",
      name_p: "Jane Doe",
      email_l: "Email",
      email_p: "jane@company.com",
      service_l: "What do you need?",
      goal_l: "Main goal",
      goal_p: "What does success look like in 6 months? (e.g. +40% organic traffic, rank top-3 on X queries, 30 demos/mo from SEO…)",
      context_l: "Context — current situation",
      context_p: "Stack, traffic level, previous SEO work, blockers, deadlines, budget range — anything that helps me scope.",
      budget_l: "Budget range",
      budget_opts: ["Not sure yet", "Under $5k", "$5k–$15k", "$15k–$50k", "$50k+"],
      consent: "I'd like a free 15-min discovery call before any commitment.",
      submit: "Send brief →",
      footnote: "I reply within 24h. No automated funnel, no pushy follow-up.",
    },
  },
  reassure: {
    eyebrow: "Why HIGH RANK",
    title: "Three reasons clients pick me.",
    items: [
      { num: "01", title: "3 years agency-side + 6 sites of my own.", desc: "I've shipped on enterprise stacks and on my own properties. Real skin in the game." },
      { num: "02", title: "AI methodology I actually built.", desc: "Custom MCP servers, real workflows — not a ChatGPT prompt I sell back to you." },
      { num: "03", title: "No empty promises.", desc: "Measurable outcomes only. If the audit doesn't deliver, you get a partial refund. In writing." },
    ],
  },
  manifesto: {
    quote_a: "AI ",
    quote_em: "detects",
    quote_b: ". My expertise ",
    quote_em2: "decides",
    quote_c: ".",
    sub: "That's the whole pitch. No shortcut, no fluff, no AI-written reports you'll never read.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Common questions.",
    items: [
      {
        q: "Why \"AI-powered\"?",
        a: "AI spots patterns across thousands of URLs in minutes — patterns a human would miss or take weeks to surface. My job is to filter what actually matters and turn it into decisions. The AI never decides; it accelerates.",
      },
      {
        q: "How are you different from other SEO consultants?",
        a: "Three things: I write code, I know every CMS, and I've built MCP-based workflows so the LLMs work for me, not the other way around. Most consultants either talk strategy without execution, or execute without strategy. I do both.",
      },
      {
        q: "Can I just do this myself?",
        a: "Yes — if you have 40 hours to learn the playbook and 200 hours to execute. If your time is more valuable than that, hire someone who's already done it 20 times.",
      },
      {
        q: "What guarantee do I have?",
        a: "If the audit doesn't surface enough actionable opportunities to justify the investment, I refund part of the fee. Spelled out in the contract before you pay.",
      },
      {
        q: "How long until I see results?",
        a: "Quick wins: 4–8 weeks. Real movement on competitive terms: 2–4 months. Anyone promising you week-one results is selling you something other than SEO.",
      },
    ],
  },
  finalcta: {
    title_a: "Ready to ",
    title_em: "unblock your SEO",
    title_b: "?",
    sub: "Complete audit in 3–5 days. A real action plan — not 500 rows of Excel.",
    cta_primary: "Send a brief",
    cta_secondary: "Or book a 15-min call — free",
  },
  footer: {
    left: "HIGH RANK LLC · 2025–2026",
    mid: "SEO consulting, no fluff",
    links: [
      { label: "Services", href: "#services" },
      { label: "Method", href: "#method" },
      { label: "Contact", href: "#contact" },
    ],
  },
};
